#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -N detect_alpha_peak

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso, Aurore Bussalb


set -e
set -x

# Make output directories
mkdir -p out_dir
mkdir -p out_dir2

# Run the actual python code
singularity exec docker://brainlife/mne:0.23dev python3 main.py

# Store PSD plot with alpha peak on product.json
cat << EOF > product.json
{
    "brainlife": [
        { 
            "type": "image/png", 
	        "name": "Alpha peak frequencies",
            "base64": "$(base64 -w 0 out_figs/hist_alpha_peak.png)"
        }
    ]
}
EOF


